[profile.default]
src = './'
test = './test'
out = './out'
libs = ["../../node_modules", "node_modules", "./lib"]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config