# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
src = './contracts'
test = './contracts'
cache = true
cache_path = '.hybrid/cache'
out = '.hybrid/out'
libs = ["node_modules"]
gas_reports = ["*"]