name: SDK tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn --cwd packages/react build

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          profile: minimal
          override: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Launch Anvil
        run: FORK_URL=${{ secrets.FORK_URL }} yarn anvil &

      - name: Test
        run: yarn --cwd packages/react test
        env:
          VANITY_ADDRESS: ${{ secrets.VANITY_ADDRESS }}
          VANITY_PK: ${{ secrets.VANITY_PK }}

      # - name: Coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./packages/react/coverage.lcov
